const appendices = [
  {
    id: "appendix-a",
    title: "Appendix A: Grafrover",
    notes: [
      "* = Alleen als eenmalige actie nog niet is gebruikt",
      "✓ = Rol krijgt eenmalige actie terug",
      "- = Niet Te gebruiken",
      "J = Normaal Gebruik"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", "-"],
      ["Genezer", "J"],
      ["Ziener", "J"],
      ["Jager", "✓"],
      ["Cupido", "*"],
      ["Onschuldige Sletje", "J"],
      ["Burgerlijke Burger", "-"],
      ["Aasgier", "J"],
      ["Agent", "J"],
      ["Alwetende Uil", "-"],
      ["Bommenwerper", "J"],
      ["Charmante Dealer", "J"],
      ["Dictator", "*"],
      ["Dodenbezweerder", "-"],
      ["Dokter", "Levens *, Doods *"],
      ["Dorpsgek", "✓"],
      ["Dorpsoudste", "✓"],
      ["Grafrover", "-"],
      ["Husselaar", "*"],
      ["Hypocriet", "J"],
      ["Jaloerse Ex", "J"],
      ["Journalist", "J"],
      ["Klier", "J"],
      ["Leerling", "-"],
      ["Omroeper", "J"],
      ["Onderduiker", "J"],
      ["Papegaai", "J"],
      ["Rebel", "*"],
      ["Ridder met het Roestige Zwaard", "✓"],
      ["Samurai", "*"],
      ["Siamese Tweeling", "-"],
      ["Smid", "J"],
      ["Stalker", "J"],
      ["Stotterende Raadsheer", "*"],
      ["Toneelspeler", "* Overige Rollen"],
      ["Twijfelaar", "✓"],
      ["Valse Erfgenaam", "Alleen Valse Rol"],
      ["Verkenner", "J"],
      ["Veteraan", "✓"],
      ["Verwarde Ziener", "J"],
      ["Vos", "J"],
      ["Vriend", "J"],
      ["Waakengel", "-"],
      ["Wachter", "-"],
      ["Wethouder", "-"],
      ["Wingman", "J"],
      ["Zondebok", "✓"],
      ["Harige Harry", "J"],
      ["Medium", "J"],
      ["Toegewijde Dienstmeisje", "-"],
      ["Zwarte Schaap", "*"],
      ["Besmettelijke Raaf", "J Beide"],
      ["Fluitspeler", "J"],
      ["Illusionist", "J"],
      ["Onzekere Grenswachter", "-"],
      ["Premiejager", "-"],
      ["Pyromaan", "J"],
      ["Twee Gescheiden Gezusters", "-"],
      ["Verloren Ziel", "-"],
      ["Witte Weerwolf", "-"],
      ["Weerwolf", "-"],
      ["Kleine Wilde", "-"],
      ["Verdoemde", "-"],
      ["Besmettelijke Oerwolf", "J"],
      ["Boze Wolf", "J"],
      ["Conciërge", "J"],
      ["Feestwolf", "*"],
      ["Glitterende Toverwolf", "J"],
      ["Heks", "J"],
      ["Jachtwolf", "✓"],
      ["Onderdrukker", "J"],
      ["Slager", "-"],
      ["Verlammer", "-"],
      ["Vervloekte Wolf", "-"],
      ["Welp", "-"],
      ["Wolf in Schaapskleren", "J"],
      ["Wolf in Winterslaap", "✓"],
      ["Wolfsoudste", "✓"],
      ["Wolfsschrijver", "J"],
      ["Wolvenmeester", "-"],
      ["Wolfsspook", "-"],
      ["Barman Bob", "J"],
      ["Barman Bert", "J"],
      ["Waarzegster", "J"],
      ["Oma", "-"],
      ["Grote Boze Wolf", "-"],
      ["Roodkapje", "-"]
    ]
  },
  {
    id: "appendix-b",
    title: "Appendix B: Papegaai",
    notes: [
      "- = Niet te kopiëren",
      "* = Geen actie om te kopiëren",
      "J = normaal gebruik, Anders uitleg"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", "*"],
      ["Genezer", "J"],
      ["Ziener", "J"],
      ["Jager", "J, alleen nacht"],
      ["Cupido", "J"],
      ["Onschuldige Sletje", "J"],
      ["Burgerlijke Burger", "*"],
      ["Aasgier", "-"],
      ["Agent", "J"],
      ["Alwetende Uil", "-"],
      ["Bommenwerper", "J"],
      ["Charmante Dealer", "J"],
      ["Dictator", "*"],
      ["Dodenbezweerder", "-"],
      ["Dokter", "Levens -, Doods J"],
      ["Dorpsgek", "*"],
      ["Dorpsoudste", "J, mocht je die nacht sterven door een wolf"],
      ["Grafrover", "J, vraag om dode"],
      ["Husselaar", "J"],
      ["Hypocriet", "J"],
      ["Jaloerse Ex", "J"],
      ["Journalist", "-"],
      ["Klier", "J"],
      ["Leerling", "J, alleen uitgeleerd"],
      ["Omroeper", "-"],
      ["Onderduiker", "*"],
      ["Papegaai", "-"],
      ["Rebel", "*"],
      ["Ridder met het Roestige Zwaard", "J, mocht je die nacht sterven door een wolf"],
      ["Samurai", "-"],
      ["Siamese Tweeling", "*"],
      ["Smid", "J"],
      ["Stalker", "J"],
      ["Stotterende Raadsheer", "J"],
      ["Toneelspeler", "J, liggend aan de gekozen rol"],
      ["Twijfelaar", "*"],
      ["Valse Erfgenaam", "J, alleen valse rol"],
      ["Verkenner", "J"],
      ["Veteraan", "J, mocht je die nacht sterven"],
      ["Verwarde Ziener", "J"],
      ["Vos", "J"],
      ["Vriend", "J"],
      ["Waakengel", "-"],
      ["Wachter", "-"],
      ["Wethouder", "J, alleen aangenomen rol"],
      ["Wingman", "J"],
      ["Zondebok", "-"],
      ["Harige Harry", "*"],
      ["Medium", "J"],
      ["Toegewijde Dienstmeisje", "-"],
      ["Zwarte Schaap", "J"],
      ["Besmettelijke Raaf", "J, gebruik zelfde actie als De Raaf"],
      ["Fluitspeler", "J"],
      ["Illusionist", "J, gebruik zelfde actie als de Illusionist"],
      ["Onzekere Grenswachter", "-*"],
      ["Premiejager", "J, alleen markering"],
      ["Pyromaan", "J, gebruik zelfde actie als De Pyromaan"],
      ["Twee Gescheiden Gezusters", "-"],
      ["Verloren Ziel", "-*"],
      ["Witte Weerwolf", "J, mist als diegene geen wolf is. Alleen als Witte Weerwolf actie gebruikt."],
      ["Weerwolf", "*"],
      ["Kleine Wilde", "*"],
      ["Verdoemde", "*"],
      ["Besmettelijke Oerwolf", "-"],
      ["Boze Wolf", "J"],
      ["Conciërge", "J"],
      ["Feestwolf", "-"],
      ["Glitterende Toverwolf", "J"],
      ["Heks", "J"],
      ["Jachtwolf", "J, alleen nacht"],
      ["Onderdrukker", "J"],
      ["Slager", "-"],
      ["Verlammer", "-"],
      ["Vervloekte Wolf", "-"],
      ["Welp", "J"],
      ["Wolf in Schaapskleren", "J"],
      ["Wolf in Winterslaap", "-"],
      ["Wolfsoudste", "J, mocht je die nacht sterven door alles behalve een wolf"],
      ["Wolfsschrijver", "J"],
      ["Wolvenmeester", "*"],
      ["Wolfsspook", "-"],
      ["Barman Bob", "J"],
      ["Barman Bert", "J"],
      ["Waarzegster", "-*"],
      ["Oma", "-"],
      ["Grote Boze Wolf", "-"],
      ["Roodkapje", "*"],
      ["Verslinder van de Nacht (Weerwolf)", "J, normale actie van de Weerwolf gaat voor. Voorbeeld: Heks is Verslinder; Heks actie wordt gekopieerd. Wolf met geen of niet kopiërbare dus wel meteen de nachtelijke kill."]
    ]
  },
  {
    id: "appendix-c",
    title: "Appendix C: Toneelspeler Rollen",
    notes: [
      "J = Wel",
      "N = Niet"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", "J"],
      ["Genezer", "N"],
      ["Ziener", "N"],
      ["Jager", "N"],
      ["Cupido", "N"],
      ["Onschuldige Sletje", "N"],
      ["Burgerlijke Burger", "N"],
      ["Aasgier", "J"],
      ["Agent", "J"],
      ["Alwetende Uil", "J"],
      ["Bommenwerper", "J"],
      ["Charmante Dealer", "J"],
      ["Dictator", "J"],
      ["Dodenbezweerder", "N"],
      ["Dokter", "N"],
      ["Dorpsgek", "J"],
      ["Dorpsoudste", "J"],
      ["Grafrover", "J"],
      ["Husselaar", "J"],
      ["Hypocriet", "J"],
      ["Jaloerse Ex", "J"],
      ["Journalist", "N"],
      ["Klier", "J"],
      ["Leerling", "N"],
      ["Omroeper", "J"],
      ["Onderduiker", "J"],
      ["Papegaai", "J"],
      ["Rebel", "J"],
      ["Ridder met het Roestige Zwaard", "J"],
      ["Samurai", "J"],
      ["Siamese Tweeling", "N"],
      ["Smid", "J"],
      ["Stalker", "J"],
      ["Stotterende Raadsheer", "J"],
      ["Toneelspeler", "N"],
      ["Twijfelaar", "J"],
      ["Valse Erfgenaam", "N"],
      ["Verkenner", "J"],
      ["Veteraan", "N"],
      ["Verwarde Ziener", "J"],
      ["Vos", "J"],
      ["Vriend", "J"],
      ["Waakengel", "N"],
      ["Wachter", "N"],
      ["Wethouder", "N"],
      ["Wingman", "J"],
      ["Zondebok", "J"],
      ["Harige Harry", "J"],
      ["Medium", "J"],
      ["Toegewijde Dienstmeisje", "N"],
      ["Zwarte Schaap", "J"],
      ["Besmettelijke Raaf", "N"],
      ["Fluitspeler", "N"],
      ["Illusionist", "N"],
      ["Onzekere Grenswachter", "N"],
      ["Premiejager", "N"],
      ["Pyromaan", "N"],
      ["Twee Gescheiden Gezusters", "N"],
      ["Verloren Ziel", "N"],
      ["Witte Weerwolf", "N"],
      ["Weerwolf", "J"],
      ["Kleine Wilde", "N"],
      ["Verdoemde", "N"],
      ["Besmettelijke Oerwolf", "N"],
      ["Boze Wolf", "J"],
      ["Conciërge", "J"],
      ["Feestwolf", "J"],
      ["Glitterende Toverwolf", "J"],
      ["Heks", "J"],
      ["Jachtwolf", "J"],
      ["Onderdrukker", "J"],
      ["Slager", "N"],
      ["Verlammer", "N"],
      ["Vervloekte Wolf", "N"],
      ["Welp", "N"],
      ["Wolf in Schaapskleren", "J"],
      ["Wolf in Winterslaap", "N"],
      ["Wolfsoudste", "J"],
      ["Wolfsschrijver", "J"],
      ["Wolvenmeester", "J"],
      ["Wolfsspook", "N"],
      ["Barman Bob", "N"],
      ["Barman Bert", "N"],
      ["Waarzegster", "N"],
      ["Oma", "N"],
      ["Grote Boze Wolf", "N"],
      ["Roodkapje", "N"]
    ]
  },
  {
    id: "appendix-d",
    title: "Appendix D: Dronken",
    notes: [
      "* Geen actie / Dronkbare Actie",
      "✔️ Simpelweg gericht op een andere speler"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", "*"],
      ["Genezer", "✔️"],
      ["Ziener", "✔️"],
      ["Jager", "Laatste kogel word op iemand anders gericht"],
      ["Cupido", "✔️ Personen"],
      ["Onschuldige Sletje", "✔️"],
      ["Burgerlijke Burger", "*"],
      ["Aasgier", "✔️"],
      ["Agent", "✔️"],
      ["Alwetende Uil", "*"],
      ["Bommenwerper", "✔️"],
      ["Charmante Dealer", "✔️"],
      ["Dictator", "*"],
      ["Dodenbezweerder", "Willekeurig Offer"],
      ["Dokter", "*"],
      ["Dorpsgek", "Ontmaskerd zichzelf"],
      ["Dorpsoudste", "Krijgt te horen dat hij is aangevallen, terwijl hij dat niet is"],
      ["Grafrover", "Willekeurige Dode"],
      ["Husselaar", "*"],
      ["Hypocriet", "Krijgt te horen dat hij door een willekeurig persoon bezocht is"],
      ["Jaloerse Ex", "✔️"],
      ["Journalist", "✔️"],
      ["Klier", "✔️"],
      ["Leerling", "Liggend aan hoe hij uitgeleerd is"],
      ["Omroeper", "*"],
      ["Onderduiker", "Krijgt te horen dat hij bekeken is"],
      ["Papegaai", "Willekeurige persoon kopieeren, richt diens actie wel op iemand na keuze"],
      ["Rebel", "*"],
      ["Ridder met het Roestige Zwaard", "*"],
      ["Samurai", "*"],
      ["Siamese Tweeling", "*"],
      ["Smid", "✔️"],
      ["Stalker", "✔️"],
      ["Stotterende Raadsheer", "*"],
      ["Toneelspeler", "Kan dronken zijn terwijl hij zijn rol speeld"],
      ["Twijfelaar", "*"],
      ["Valse Erfgenaam", "✔️"],
      ["Verkenner", "✔️"],
      ["Veteraan", "Krijgt te horen dat zijn adrenaline boost in werking is gezet"],
      ["Verwarde Ziener", "Krijgt de correcte informatie"],
      ["Vos", "3 willekeurige personen"],
      ["Vriend", "✔️"],
      ["Waakengel", "*"],
      ["Wachter", "Sluit een willekeurig persoon op, niet de gemelde in de ochtend"],
      ["Wethouder", "Liggend aan wie burgemeester is"],
      ["Wingman", "2 willekeurige personen"],
      ["Zondebok", "*"],
      ["Harige Harry", "*"],
      ["Medium", "*"],
      ["Toegewijde Dienstmeisje", "*"],
      ["Zwarte Schaap", "*"],
      ["Besmettelijke Raaf", "Besmetting ✔️, moord ✔️"],
      ["Fluitspeler", "✔️ Personen"],
      ["Illusionist", "✔️ vermomming"],
      ["Onzekere Grenswachter", "*"],
      ["Premiejager", "✔️ Markering"],
      ["Pyromaan", "Als hij iemand ondergiet ✔️"],
      ["Twee Gescheiden Gezusters", "✔️"],
      ["Verloren Ziel", "*"],
      ["Witte Weerwolf", "✔️ Willekeurige Wolf"],
      ["Weerwolf", "*"],
      ["Kleine Wilde", "*"],
      ["Verdoemde", "*"],
      ["Besmettelijke Oerwolf", "*"],
      ["Boze Wolf", "✔️"],
      ["Conciërge", "✔️"],
      ["Feestwolf", "✔️"],
      ["Glitterende Toverwolf", "✔️"],
      ["Heks", "✔️"],
      ["Jachtwolf", "Laatste kogel word op iemand anders gericht"],
      ["Onderdrukker", "✔️"],
      ["Slager", "✔️, marineren keuze"],
      ["Verlammer", "*"],
      ["Vervloekte Wolf", "*"],
      ["Welp", "✔️, gokt een rol op willekeurige speler"],
      ["Wolf in Schaapskleren", "✔️"],
      ["Wolf in Winterslaap", "willekeurig persoon opeten bij ontwaak"],
      ["Wolfsoudste", "Krijgt te horen dat hij is aangevallen, terwijl hij dat niet is"],
      ["Wolfsschrijver", "Willekeurige Beschrijving"],
      ["Wolvenmeester", "*"],
      ["Wolfsspook", "*"],
      ["Barman Bob", "✔️"],
      ["Barman Bert", "✔️"],
      ["Waarzegster", "*"],
      ["Oma", "Kan niet dronken worden"],
      ["Grote Boze Wolf", "Kan niet dronken worden"],
      ["Roodkapje", "*"]
    ]
  },
  {
    id: "appendix-e",
    title: "Appendix E: Niet aanneembare rollen",
    notes: [
      "U = Niet aanneembaar door De Alwetende Uil",
      "V = Niet aanneembaar door de Valse Erfgenaam",
      "D = Niet aanneembaar door het Toegewijde Dienstmeisje",
      "L = Niet aanneembaar door de Leerling",
      "W = Niet aanneembaar door de Wethouder"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", ""],
      ["Genezer", "U"],
      ["Ziener", ""],
      ["Jager", ""],
      ["Cupido", "U"],
      ["Onschuldige Sletje", "U"],
      ["Burgerlijke Burger", ""],
      ["Aasgier", ""],
      ["Agent", ""],
      ["Alwetende Uil", "U"],
      ["Bommenwerper", ""],
      ["Charmante Dealer", ""],
      ["Dictator", ""],
      ["Dodenbezweerder", ""],
      ["Dokter", ""],
      ["Dorpsgek", ""],
      ["Dorpsoudste", ""],
      ["Grafrover", ""],
      ["Husselaar", ""],
      ["Hypocriet", ""],
      ["Jaloerse Ex", ""],
      ["Journalist", ""],
      ["Klier", ""],
      ["Leerling", "L"],
      ["Omroeper", ""],
      ["Onderduiker", ""],
      ["Papegaai", ""],
      ["Rebel", ""],
      ["Ridder met het Roestige Zwaard", ""],
      ["Samurai", ""],
      ["Siamese Tweeling", "UVDLW"],
      ["Smid", ""],
      ["Stalker", ""],
      ["Stotterende Raadsheer", ""],
      ["Toneelspeler", ""],
      ["Twijfelaar", ""],
      ["Valse Erfgenaam", "V"],
      ["Verkenner", ""],
      ["Veteraan", ""],
      ["Verwarde Ziener", ""],
      ["Vos", ""],
      ["Vriend", ""],
      ["Waakengel", ""],
      ["Wachter", ""],
      ["Wethouder", "W"],
      ["Wingman", ""],
      ["Zondebok", ""],
      ["Harige Harry", ""],
      ["Medium", ""],
      ["Toegewijde Dienstmeisje", ""],
      ["Zwarte Schaap", ""],
      ["Besmettelijke Raaf", "U"],
      ["Fluitspeler", "U"],
      ["Illusionist", "U"],
      ["Onzekere Grenswachter", "U"],
      ["Premiejager", "U"],
      ["Pyromaan", "U"],
      ["Twee Gescheiden Gezusters", "UVDLW"],
      ["Verloren Ziel", "U"],
      ["Witte Weerwolf", "U"],
      ["Weerwolf", "U"],
      ["Kleine Wilde", "U"],
      ["Verdoemde", "U"],
      ["Besmettelijke Oerwolf", "U"],
      ["Boze Wolf", "U"],
      ["Conciërge", "U"],
      ["Feestwolf", "U"],
      ["Glitterende Toverwolf", "U"],
      ["Heks", "U"],
      ["Jachtwolf", "U"],
      ["Onderdrukker", "U"],
      ["Slager", "U"],
      ["Verlammer", "U"],
      ["Vervloekte Wolf", "U"],
      ["Welp", "U"],
      ["Wolf in Schaapskleren", "U"],
      ["Wolf in Winterslaap", "U"],
      ["Wolfsoudste", "U"],
      ["Wolfsschrijver", "U"],
      ["Wolvenmeester", "U"],
      ["Wolfsspook", "U"],
      ["Barman Bob", "U"],
      ["Barman Bert", "U"],
      ["Waarzegster", "U"],
      ["Oma", "UVDLW"],
      ["Grote Boze Wolf", "UVDLW"],
      ["Roodkapje", "UVDLW"]
    ]
  },
  {
    id: "appendix-f",
    title: "Appendix F: De Smid",
    notes: [
      "0 = Simpelweg extra persoon",
      "- = Niet te verbeteren"
    ],
    columns: ["Rol", "Info"],
    rows: [
      ["Burger", "Actie naar keuze"],
      ["Genezer", "0"],
      ["Ziener", "0"],
      ["Jager", "Extra kogel"],
      ["Cupido", "0"],
      ["Onschuldige Sletje", "Zowel de Slet en de Host zijn niet thuis"],
      ["Burgerlijke Burger", "Nogmaals aangekondigd"],
      ["Aasgier", "0"],
      ["Agent", "0"],
      ["Alwetende Uil", "Extra Keus, anders liggend aan gekozen rol"],
      ["Bommenwerper", "Twee Bommen"],
      ["Charmante Dealer", "0"],
      ["Dictator", "Tijdelijke gratis actie"],
      ["Dodenbezweerder", "-"],
      ["Dokter", "Extra tijdelijk gratis drankje naar keuze"],
      ["Dorpsgek", "-, als hij wel ontmaskerd is mag hij wel stemmen voor die dag"],
      ["Dorpsoudste", "Actie wordt niet verbruikt"],
      ["Grafrover", "Levende speler kiezen"],
      ["Husselaar", "0"],
      ["Hypocriet", "Mag de actie van de Verkenner gebruiken"],
      ["Jaloerse Ex", "0"],
      ["Journalist", "-"],
      ["Klier", "0"],
      ["Leerling", "Liggend aan de afgestudeerde rol"],
      ["Omroeper", "Een persoon naar keuze zijn rol aankondigen"],
      ["Onderduiker", "0"],
      ["Papegaai", "Actie wordt niet verbruikt"],
      ["Rebel", "Blijft leven na een aanval"],
      ["Ridder met het Roestige Zwaard", "0"],
      ["Samurai", "0"],
      ["Siamese Tweeling", "-"],
      ["Smid", "-"],
      ["Stalker", "0"],
      ["Stotterende Raadsheer", "Nog een extra brandstapel"],
      ["Toneelspeler", "Liggend aan gekozen rol"],
      ["Twijfelaar", "De op 2 na meeste stemmen gaat ook mee"],
      ["Valse Erfgenaam", "0, anders liggend aan Valse Rol"],
      ["Verkenner", "0"],
      ["Veteraan", "Overleefd 2 dagen als diegene die nacht word aangevallen"],
      ["Verwarde Ziener", "0"],
      ["Vos", "0"],
      ["Vriend", "0, keuze (wel of niet)"],
      ["Waakengel", "Gratis Bescherming"],
      ["Wachter", "Risicoloze moord"],
      ["Wethouder", "Liggend aan Burgemeester rol"],
      ["Wingman", "0"],
      ["Zondebok", "Mag deze nacht de stemmers van de volgende dag bepalen"],
      ["Harige Harry", "Ziet er uit als Burger"],
      ["Medium", "2 vragen"],
      ["Toegewijde Dienstmeisje", "-, anders liggend aan overgenomen rol"],
      ["Zwarte Schaap", "Wolven krijgen 1/3 ipv 1/2"],
      ["Besmettelijke Raaf", "Besmet 0, kill 0"],
      ["Fluitspeler", "0"],
      ["Illusionist", "0"],
      ["Onzekere Grenswachter", "-"],
      ["Premiejager", "-"],
      ["Pyromaan", "0"],
      ["Twee Gescheiden Gezusters", "0"],
      ["Verloren Ziel", "Tweede kans, die nacht"],
      ["Witte Weerwolf", "-"],
      ["Weerwolf", "Mag een speler verslinden"],
      ["Kleine Wilde", "-"],
      ["Verdoemde", "-"],
      ["Besmettelijke Oerwolf", "-"],
      ["Boze Wolf", "0, of als een weerwolf al dood is mag hij wel nog een moord plegen"],
      ["Conciërge", "0"],
      ["Feestwolf", "0"],
      ["Glitterende Toverwolf", "0"],
      ["Heks", "0"],
      ["Jachtwolf", "Twee kogels"],
      ["Onderdrukker", "0"],
      ["Slager", "Marineren 0"],
      ["Verlammer", "-"],
      ["Vervloekte Wolf", "-"],
      ["Welp", "0"],
      ["Wolf in Schaapskleren", "Wisselt van rol identiteit"],
      ["Wolf in Winterslaap", "Blijft slapen, maar moord wel zijn bezoeker"],
      ["Wolfsoudste", "Actie niet verbruikt"],
      ["Wolfsschrijver", "Actie niet verbruikt"],
      ["Wolvenmeester", "-"],
      ["Wolfsspook", "-"],
      ["Barman Bob", "0"],
      ["Barman Bert", "0"],
      ["Waarzegster", "-"],
      ["Oma", "-"],
      ["Grote Boze Wolf", "-"],
      ["Roodkapje", "-"]
    ]
  }
];