const talents = [
  { category: "Bekend", name: "Jachtig", description: "Bij je **dood** mag je direct een speler aanwijzen die met jou sterft.", originalRole: "De Jager / De Jachtwolf", note: "De Jager en De Jachtwolf worden niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Overlever", description: "Wanneer je dodelijk wordt getroffen, blijf je nog een volledige dag in leven.", originalRole: "De Veteraan", note: "De Veteraan wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Openbarend", description: "Kies aan het begin van het spel een speler. Wanneer jij sterft, wordt ook de rol van die speler bekendgemaakt.", originalRole: "De Omroeper", note: "De Omroeper wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Oudbloed", description: "Overleeft een aanval van de tegenpartij.", originalRole: "De Dorpsoudste / De Wolfsoudste", note: "De Dorpsoudste en De Wolfsoudste worden niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Wraakzwaard", description: "Wanneer je door de tegenpartij wordt gedood, neem je de veroorzaker mee het graf in.", originalRole: "De Ridder met het Roestige Zwaard", note: "De Ridder met het Roestige Zwaard wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Hypocritisch", description: "Krijgt iedere nacht te horen wie hem bezocht heeft.", originalRole: "De Hypocriet", note: "De Hypocriet wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Waanzinnig", description: "Overleeft de eerste brandstapel, maar verliest daarna zijn stemrecht.", originalRole: "De Dorpsgek", note: "De Dorpsgek wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Zondebok", description: "Wordt opgeofferd wanneer een stemming in een gelijke stand eindigt.", originalRole: "De Zondebok", note: "De Zondebok wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Harig", description: "Wordt bij onderzoeken altijd gezien als weerwolf.", originalRole: "Harige Harry", note: "Harige Harry wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Heerszuchtig", description: "Mag eenmaal per spel de uitslag van een stemming vervangen door een speler naar keuze.", originalRole: "De Dictator", note: "De Dictator wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Eervol", description: "Mag zichzelf opofferen om samen met een gekozen speler te sterven.", originalRole: "De Samurai", note: "De Samurai wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Siamees", description: "Is vanaf het begin van het spel gekoppeld aan een andere speler. Acties op een van beiden werken op allebei en zij stemmen altijd hetzelfde.", originalRole: "De Siamese Tweeling", note: "De Siamese Tweeling wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Stotterend", description: "Mag eenmaal per spel bepalen dat er de volgende dag een extra stemronde plaatsvindt.", originalRole: "De Stotterende Raadsheer", note: "De Stotterende Raadsheer wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Rebels", description: "Mag eenmaal per spel de burgemeester uitschakelen en een nieuwe verkiezing afdwingen.", originalRole: "De Rebel", note: "De Rebel wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Verdoemd", description: "Wordt een weerwolf wanneer hij slachtoffer wordt van een wolvenaanval. Zijn oorspronkelijke rol blijft behouden.", originalRole: "De Verdoemde", note: "De Verdoemde wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Wildbloed", description: "Kiest aan het begin van het spel een meester. Sterft deze speler, dan sluit hij zich aan bij de weerwolven terwijl hij zijn rol behoudt.", originalRole: "De Kleine Wilde", note: "De Kleine Wilde wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Vervloekt", description: "Wanneer je sterft, verandert het volgende slachtoffer van een wolvenaanval in een weerwolf.", originalRole: "De Vervloekte Wolf", note: "De Vervloekte Wolf wordt niet gebruikt wanneer dit Talent actief is." },
  { category: "Bekend", name: "Eenogig", description: "Mag *eenmaal per spel* de rol van een speler bekijken.", originalRole: "De Ziener" },
  { category: "Bekend", name: "Broederschap", description: "Drie spelers weten vanaf de start dat zij bij elkaar horen en kunnen elkaar volledig vertrouwen." },
  { category: "Bekend", name: "Zusterschap", description: "Twee spelers weten vanaf de start dat zij bij elkaar horen en kunnen elkaar volledig vertrouwen." },
  { category: "Bekend", name: "Understudy", description: "Ontvangt een extra rol die hij eenmaal tijdens een nacht mag aannemen.", originalRole: "Toneelspeler" },
  { category: "Bekend", name: "Herstellend", description: "Mag eenmaal per spel een gebruikte eenmalige kracht herstellen." },
  { category: "Bekend", name: "Invloedrijk", description: "Mag eenmaal per spel een speler onderdrukken.", originalRole: "Agent / Onderdrukker" },
  { category: "Bekend", name: "Logerend", description: "Mag eenmaal per spel de nacht doorbrengen bij een andere speler.", originalRole: "Het Onschuldige Sletje" },
  { category: "Bekend", name: "Gifmenger", description: "Beschikt over een gifserum.", originalRole: "De Dokter" },
  { category: "Bekend", name: "Naprater", description: "Mag eenmaal per spel de actie van een andere speler kopieren.", originalRole: "De Papegaai" },
  { category: "Bekend", name: "Speurneus", description: "Mag eenmaal per spel een speler volgen tijdens de nacht.", originalRole: "De Verkenner" },
  { category: "Nieuw", name: "Onevenaar", description: "Kan alleen sterven op oneven dagen of tijdens oneven nachten." },
  { category: "Nieuw", name: "Evenaar", description: "Kan alleen sterven op even dagen of tijdens even nachten." },
  { category: "Nieuw", name: "Volgeling", description: "Kiest een speler en stemt altijd mee met die speler." },
  { category: "Nieuw", name: "Zwijger", description: "Mag zijn rol nooit claimen." },
  { category: "Nieuw", name: "Onruststoker", description: "Wanneer je sterft, verloopt de volgende stemming volledig anoniem." },
  { category: "Nieuw", name: "Onbekende", description: "Wanneer je sterft, wordt je rol niet bekendgemaakt." },
  { category: "Nieuw", name: "Boekhouder", description: "Weet altijd hoeveel burgers, weerwolven en onafhankelijken oorspronkelijk in het spel zaten." },
  { category: "Nieuw", name: "Volksmenner", description: "Jouw stem telt dubbel." },
  { category: "Nieuw", name: "Handelaar", description: "Mag eenmaal per spel twee Talenten tussen twee spelers omwisselen." },
  { category: "Nieuw", name: "Zuivere Ziel", description: "Wordt bij onderzoeken gezien als burger." },
  { category: "Nieuw", name: "Fanboy", description: "Kiest een speler. Zolang die speler leeft, telt jouw stem dubbel." },
  { category: "Nieuw", name: "Koppigaard", description: "Alle acties gericht op jou worden teruggekaatst naar de bron, behalve dodelijke acties." },
  { category: "Nieuw", name: "Kameleon", description: "Mag eenmaal per spel zijn Talent vervangen door een ongebruikt Talent." },
  { category: "Nieuw", name: "Erfgenaam", description: "Kiest een speler. Wanneer deze sterft, neem je diens Talent over." },
  { category: "Nieuw", name: "Schaduw", description: "Kan niet onderzocht worden door zienende rollen." },
  { category: "Nieuw", name: "Eenzame", description: "Kan nooit onderdeel worden van een koppel, verbond of liefdesband." },
  { category: "Nieuw", name: "Redenaar", description: "Heeft **geen chatlimiet**." },
  { category: "Nieuw", name: "Volksheld", description: "Kan niet tijdens Dag 1 op de brandstapel eindigen." },
  { category: "Nieuw", name: "Verrader", description: "Mag bij zijn dood een speler aanwijzen die permanent zijn stemrecht verliest." }
];